spring:
  application:
    name: service-b
server:
  port: 8801
eureka:
  instance:
    instance-id: inst001

  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8761/eureka/