spring:
  application:
    name: service-a
server:
  port: 8800
eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8761/eureka/