spring:
  application:
    name: api-gateway
server:
  port: 8802

eureka:
  instance:
    instance-id: zuul-inst001
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
